Install jupyter-book along with cookiecutter
The hooks seem to import jupyter-book, so the
instructions as provided fail with the following error:

```
3 - no
Choose from 1, 2, 3 [1]: 1
Traceback (most recent call last):
  File "/var/folders/p4/gnx7h_mj73v92nj_v93475v80000gn/T/tmpe50bxgoh.py", line 5, in <module>
    import jupyter_book
ModuleNotFoundError: No module named 'jupyter_book'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```